### ISSUE TITLE
Service duplicate entry in sql

### ISSUE THREAD

**Issue by cyberb** [syncloud/redirect#16]
````
------------------------------------------------------------
Traceback (most recent call last):
File "/usr/lib/python2.7/logging/__init__.py", line 851, in emit
 msg = self.format(record)
File "/usr/lib/python2.7/logging/__init__.py", line 724, in format
 return fmt.format(record)
File "/usr/lib/python2.7/logging/__init__.py", line 464, in format
 record.message = record.getMessage()
File "/usr/lib/python2.7/logging/__init__.py", line 328, in getMessage
 msg = msg % self.args
TypeError: not all arguments converted during string formatting
Logged from file storage.py, line 86
------------------------------------------------------------
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
 rv = self.dispatch_request()
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
 return self.view_functions[rule.endpoint](**req.view_args)
File "/usr/local/lib/python2.7/dist-packages/flask_cors.py", line 104, in wrapped_function
 resp = make_response(f(*args, **kwargs))
File "***/redirect/rest.py", line 59, in domain_update
 domain = manager().domain_update(request_data)
File "***/redirect/services.py", line 226, in domain_update
 return domain
File "***/redirect/storage.py", line 88, in __exit__
 raise e
IntegrityError: (IntegrityError) (1062, "Duplicate entry '178-10000' for key 'domain_id'")
'INSERT INTO service (name, protocol, type, url, port, domain_id) ' \
'VALUES (%s, %s, %s, %s, %s, %s)' \
 (u'ownCloud', u'https', u'_owncloud._https._tcp', u'owncloud', 10000, 178L)

````

**Comment by cyberb** [comment]
Adding more info:

**Insider command:**
url: http://api.syncloud.info:81/domain/update
request: {"services": [], "token": "****", "local_ip": "127.0.0.2"}

**Redirect log:**
ERROR:root:added: []
root:removed: [{name: image-ci, protocol: http, type: image-ci, port: 80, local_port: 80, url:
image-ci}, {name: image-ci, protocol: http, type: image-ci, port: 80, local_port: 80, url: image-ci},{ name: ownCloud, protocol: http, type: _owncloud._http._
tcp, port: 80, local_port: 80, url: owncloud}, {name: ownCloud, protocol: http, type: _owncloud._http._tcp, port: 80, local_port: 80, url: owncloud}, {name: s
erver, protocol: http, type: server, port: 80, local_port: 80}, {name: server, protocol: http, type: server, port: 80, local_port: 80}, {name: ssh, protocol:
ssh, type: _ssh._tcp, port: 1022, local_port: 1022, url: ssh]

**Sql:**
mysql> select * from service where domain_id = 222;
+-------+----------+----------+----------------------+----------+------+------------+-----------+---------------------+
| id    | name     | protocol | type                 | url      | port | local_port | domain_id | timestamp           |
+-------+----------+----------+----------------------+----------+------+------------+-----------+---------------------+
| 10144 | image-ci | http     | image-ci             | image-ci |   80 |         80 |       222 | 2015-03-19 17:30:07 |
| 10147 | image-ci | http     | image-ci             | image-ci |   80 |         80 |       222 | 2015-03-19 17:30:09 |
| 10143 | ownCloud | http     | _owncloud._http._tcp | owncloud |   80 |         80 |       222 | 2015-03-19 17:30:07 |
| 10146 | ownCloud | http     | _owncloud._http._tcp | owncloud |   80 |         80 |       222 | 2015-03-19 17:30:09 |
| 10142 | server   | http     | server               | NULL     |   80 |         80 |       222 | 2015-03-19 17:30:07 |
| 10145 | server   | http     | server               | NULL     |   80 |         80 |       222 | 2015-03-19 17:30:09 |
| 10139 | ssh      | ssh      | _ssh._tcp            | ssh      | 1022 |       1022 |       222 | 2015-03-19 17:28:50 |
+-------+----------+----------+----------------------+----------+------+------------+-----------+---------------------+

**Dns:**
travis.syncloud.info. A
_owncloud._http._tcp.travis.syncloud.info. SRV
_ssh._tcp.travis.syncloud.info. SRV
image-ci.travis.syncloud.info. SRV
server.travis.syncloud.info. SRV


**Error:**
ERROR:root:{
[Thu Mar 19 23:04:06.526866 2015] [:error] [pid 5425]   "message": "The request contains an invalid set of changes for a resource record set 'SRV image-ci.travis.syncloud.info.'"
[Thu Mar 19 23:04:06.526877 2015] [:error] [pid 5425] }

**Comment by cyberb** [comment]
Looks like we have no constrains in test db:
````
mysql> select TABLE_SCHEMA, CONSTRAINT_NAME, TABLE_NAME, COLUMN_NAME, ORDINAL_POSITION from information_schema.KEY_COLUMN_USAGE where TABLE_NAME = 'service' and TABLE_SCHEMA in ('redirect', 'redirect_test');
+---------------+-----------------+------------+-------------+------------------+
| TABLE_SCHEMA  | CONSTRAINT_NAME | TABLE_NAME | COLUMN_NAME | ORDINAL_POSITION |
+---------------+-----------------+------------+-------------+------------------+
| redirect      | PRIMARY         | service    | id          |                1 |
| redirect      | domain_id       | service    | domain_id   |                1 |
| redirect      | domain_id       | service    | port        |                2 |
| redirect_test | PRIMARY         | service    | id          |                1 |
+---------------+-----------------+------------+-------------+------------------+
````

**Comment by vsapronov** [comment]
We agreed to make service name unique - no port, no protocol in unique constraint
